// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { DatadogMonitorSpecControllerOptions, DatadogMonitorSpecOptions } from '../datadog-operator';
import { AuditAlertType, EventAlertType, EventV2AlertType, LogAlertType, MetricAlertType, ProcessAlertType, QueryAlertType, RumAlertType, ServiceCheckType, SloAlertType, TraceAnalyticsAlertType } from './Types.generated';
import { ApiObjectMetadata } from 'cdk8s';

/**
 * Strongly typed Datadog Monitor props
 */
export interface DatadogMonitorProps {
  /**
   * Type is the monitor type.
   * @schema DatadogMonitorSpec#type
   */
  readonly type: AuditAlertType | EventAlertType | EventV2AlertType | LogAlertType | MetricAlertType | ProcessAlertType | QueryAlertType | RumAlertType | ServiceCheckType | SloAlertType | TraceAnalyticsAlertType;
  /**
   * Tags is the monitor tags associated with your monitor.
   * @schema DatadogMonitorSpec#tags
   */
  readonly tags?: Array<string>;
  /**
   * RestrictedRoles is a list of unique role identifiers to define which roles are allowed to edit the monitor.
   * `restricted_roles` is the successor of `locked`. For more information about `locked` and `restricted_roles`, see the [monitor options docs](https://docs.datadoghq.com/monitors/guide/monitor_api_options/#permissions-options).
   * @schema DatadogMonitorSpec#restrictedRoles
   */
  readonly restrictedRoles?: Array<string>;
  /**
   * Query is the Datadog monitor query.
   * @schema DatadogMonitorSpec#query
   */
  readonly query: string;
  /**
   * Priority is an integer from 1 (high) to 5 (low) indicating alert severity.
   * @schema DatadogMonitorSpec#priority
   */
  readonly priority?: number;
  /**
   * Options are the optional parameters associated with your monitor.
   * @schema DatadogMonitorSpec#options
   */
  readonly options?: DatadogMonitorSpecOptions;
  /**
   * Name is the monitor name.
   * @schema DatadogMonitorSpec#name
   */
  readonly name?: string;
  /**
   * Message is a message to include with notifications for this monitor.
   * @schema DatadogMonitorSpec#message
   */
  readonly message?: string;
  /**
   * ControllerOptions are the optional parameters in the DatadogMonitor controller.
   * @schema DatadogMonitorSpec#controllerOptions
   */
  readonly controllerOptions?: DatadogMonitorSpecControllerOptions;
  /**
   * @default Generated by Chart
   * @schema DatadogMonitor#metadata
   */
  readonly kubeMetadata?: ApiObjectMetadata;
}
