import { Construct } from "constructs";
import * as datadog from "./datadog-operator";
import { DatadogMonitorProps } from "./util";

/**
 * DatadogMonitor with strongly typed props
 */
export class DatadogMonitor extends Construct {
  constructor(scope: Construct, id: string, props: DatadogMonitorProps) {
    super(scope, id);

    // leave props.metadata undefined to have it generated by Chart:
    // https://github.com/cdk8s-team/cdk8s-core/blob/v2.67.2/src/chart.ts#L106-L131
    new datadog.DatadogMonitor(this, id, {
      metadata: props.kubeMetadata,
      spec: props,
    });
  }
}
